name: ChristmasTree
version: 1.0
description: CHRISTMAS TREEZ!!
authors: [hammale]
main: me.hammale.tree.tree
commands:
    ctree:
        description: "Use this command to generate a christmas tree!"
        usage: "ChristmasTree 1.0 commands: /ctree create"